import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import { ArrowLeft, Share2, Calendar, User, Tag, ExternalLink, ThumbsUp, ThumbsDown } from 'lucide-react';
import Header from '../components/Header';
import { useAuth } from '../../../hooks/useAuth';
import { blogService, BlogPost } from '../services/blogService';
import { getListedProducts } from '../../AgentAffiliate/services/supabaseService';
import { Product } from '../../AgentAffiliate/types';
import { ProductCard } from '../../AgentAffiliate/components/ProductCard';
import { HorizontalProductCard } from '../../AgentAffiliate/components/HorizontalProductCard';
import { AffiliateBanner } from '../../AgentAffiliate/components/AffiliateBanner';

const BlogViewerPage: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const { user } = useAuth(); // Need to import this hook above if not already used in this file scope, wait, let me check imports.
    // It is not imported. I need to add import { useAuth } from '../../../hooks/useAuth';
    const [blog, setBlog] = useState<BlogPost | null>(null);
    const [loading, setLoading] = useState(true);
    const [relatedProducts, setRelatedProducts] = useState<Product[]>([]);

    // Interaction states
    const [likes, setLikes] = useState(0);
    const [unlikes, setUnlikes] = useState(0);
    const [shares, setShares] = useState(0);
    const [userInteraction, setUserInteraction] = useState<'like' | 'unlike' | null>(null);

    const [isGenerating, setIsGenerating] = useState(false);

    useEffect(() => {
        const loadData = async () => {
            if (!id) return;
            setLoading(true);
            try {
                const blogData = await blogService.getBlogByTripId(id);

                if (blogData) {
                    setBlog(blogData);
                    setLikes(blogData.likes_count || 0);
                    setUnlikes(blogData.unlikes_count || 0);
                    setShares(blogData.shares_count || 0);

                    if (user && blogData.id) {
                        const status = await blogService.getUserInteraction(blogData.id, user.id);
                        setUserInteraction(status);
                    }

                    if (blogData.linked_products && blogData.linked_products.length > 0) {
                        const allDeals = await getListedProducts();
                        // Maintain the order generated by AI (Similarity Order)
                        const sortedDeals: Product[] = [];
                        blogData.linked_products.forEach(pid => {
                            const found = allDeals.find(p => p.id === pid);
                            if (found) sortedDeals.push(found);
                        });
                        setRelatedProducts(sortedDeals);
                    }
                }
            } catch (err) {
                console.error("Failed to load data", err);
            } finally {
                setLoading(false);
            }
        };
        loadData();
    }, [id]);

    const handleGenerate = async () => {
        if (!id) return;
        setIsGenerating(true);
        try {
            const { plansService } = await import('../services/plansService');
            const tripResult = await plansService.getPlan(id);

            if (!tripResult.success || !tripResult.data) {
                alert("Could not load trip details to generate blog.");
                return;
            }

            const { supabase } = await import('../../AgentAffiliate/services/supabaseService');
            const { data: { user } } = await supabase.auth.getUser();

            if (!user) {
                alert("You must be logged in.");
                return;
            }

            const newBlog = await blogService.generateBlogFromTrip(tripResult.data, user.id);
            if (newBlog) {
                setBlog(newBlog);
                setLikes(newBlog.likes_count || 0);
                setUnlikes(newBlog.unlikes_count || 0);
                setShares(newBlog.shares_count || 0);
                if (newBlog.linked_products && newBlog.linked_products.length > 0) {
                    const allDeals = await getListedProducts();
                    const sortedDeals: Product[] = [];
                    newBlog.linked_products.forEach(pid => {
                        const found = allDeals.find(p => p.id === pid);
                        if (found) sortedDeals.push(found);
                    });
                    setRelatedProducts(sortedDeals);
                }
            } else {
                alert("Failed to generate blog. Please try again.");
            }
        } catch (e) {
            console.error(e);
            alert("Error generating blog.");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleLike = async () => {
        if (!blog || !user) {
            alert("Please login to interact.");
            return;
        }

        // Optimistic UI Update
        const previousInteraction = userInteraction;
        const previousLikes = likes;
        const previousUnlikes = unlikes;

        if (userInteraction === 'like') {
            // Toggle OFF
            setLikes(l => l - 1);
            setUserInteraction(null);
        } else if (userInteraction === 'unlike') {
            // Switch from Unlike to Like
            setUnlikes(u => u - 1);
            setLikes(l => l + 1);
            setUserInteraction('like');
        } else {
            // New Like
            setLikes(l => l + 1);
            setUserInteraction('like');
        }

        try {
            await blogService.toggleInteraction(blog.id, user.id, 'like');
        } catch (e) {
            console.error(e);
            // Revert on error
            setLikes(previousLikes);
            setUnlikes(previousUnlikes);
            setUserInteraction(previousInteraction);
        }
    };

    const handleUnlike = async () => {
        if (!blog || !user) {
            alert("Please login to interact.");
            return;
        }

        const previousInteraction = userInteraction;
        const previousLikes = likes;
        const previousUnlikes = unlikes;

        if (userInteraction === 'unlike') {
            // Toggle OFF
            setUnlikes(u => u - 1);
            setUserInteraction(null);
        } else if (userInteraction === 'like') {
            // Switch from Like to Unlike
            setLikes(l => l - 1);
            setUnlikes(u => u + 1);
            setUserInteraction('unlike');
        } else {
            // New Unlike
            setUnlikes(u => u + 1);
            setUserInteraction('unlike');
        }

        try {
            await blogService.toggleInteraction(blog.id, user.id, 'unlike');
        } catch (e) {
            console.error(e);
            setLikes(previousLikes);
            setUnlikes(previousUnlikes);
            setUserInteraction(previousInteraction);
        }
    };

    const handleShare = async () => {
        if (!blog) return;
        navigator.clipboard.writeText(window.location.href);
        setShares(prev => prev + 1);
        alert("Magic link copied!");
        try {
            await blogService.incrementShare(blog.id);
        } catch (e) {
            console.error(e);
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-white flex items-center justify-center">
                <div className="flex flex-col items-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-teal-600 mb-4" />
                    <p className="text-gray-500 font-medium animate-pulse">Curating your experience...</p>
                </div>
            </div>
        );
    }

    if (!blog) {
        return (
            <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4 text-center">
                <div className="relative mb-10">
                    <div className="absolute inset-0 bg-teal-400 blur-3xl opacity-20 rounded-full animate-pulse" />
                    <div className="relative w-24 h-24 bg-white rounded-3xl shadow-xl flex items-center justify-center transform rotate-3 hover:rotate-0 transition-transform duration-500">
                        <Share2 className="w-12 h-12 text-teal-600" />
                    </div>
                </div>
                <h2 className="text-4xl font-black text-gray-900 mb-4 tracking-tight">Tell Your Story</h2>
                <p className="text-gray-600 max-w-lg mb-12 text-lg leading-relaxed">
                    Transform your data-rich itinerary into a premium travel journal.
                    Our AI editor crafts semantic matches and authoritative storytelling in seconds.
                </p>

                <button
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="group relative flex items-center space-x-3 bg-gray-900 text-white px-10 py-5 rounded-2xl font-bold text-xl shadow-2xl hover:shadow-teal-500/20 hover:-translate-y-1 transition-all disabled:opacity-70 active:scale-95"
                >
                    {isGenerating ? (
                        <>
                            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-white" />
                            <span>Crafting Narrative...</span>
                        </>
                    ) : (
                        <>
                            <span>Generate AI Journal</span>
                            <ArrowLeft className="w-6 h-6 rotate-180 group-hover:translate-x-1 transition-transform" />
                        </>
                    )}
                </button>

                <button
                    onClick={() => navigate(-1)}
                    className="mt-8 text-gray-400 hover:text-gray-900 font-semibold text-sm transition-colors"
                >
                    Back to Collection
                </button>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white font-sans text-slate-900 pb-32">
            <Header showBackground={true} />

            {/* Premium Hero Section */}
            <div className="relative h-[75vh] w-full overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-b from-black/20 via-transparent to-black/80 z-10" />
                <img
                    src={blog.hero_image_url}
                    alt={blog.title}
                    className="w-full h-full object-cover scale-105"
                />
                <div className="absolute inset-x-0 bottom-0 z-20 pb-16 md:pb-24 px-6">
                    <div className="max-w-5xl mx-auto">
                        <div className="flex items-center space-x-3 text-teal-300 text-xs font-black uppercase tracking-[0.2em] mb-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
                            <span className="bg-teal-500/20 backdrop-blur-md px-3 py-1 rounded-full border border-teal-500/30">Premium Travel Journal</span>
                            <span className="opacity-50">•</span>
                            <span>{new Date(blog.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</span>
                        </div>
                        <h1 className="text-4xl md:text-6xl lg:text-7xl font-extrabold text-white leading-[1.1] mb-8 animate-in fade-in slide-in-from-bottom-6 duration-1000 tracking-tight">
                            {blog.title}
                        </h1>
                        <div className="flex flex-wrap items-center gap-6 text-gray-300 text-sm font-medium animate-in fade-in slide-in-from-bottom-8 duration-1000">
                            <div className="flex items-center space-x-2.5 bg-white/10 backdrop-blur-xl px-4 py-2 rounded-full border border-white/10">
                                <User className="w-4 h-4 text-teal-400" />
                                <span>WanderWriter AI Editor</span>
                            </div>
                            {blog.tags && (
                                <div className="flex items-center gap-2">
                                    {blog.tags.map(tag => (
                                        <span key={tag} className="bg-gray-900/40 backdrop-blur-xl px-3 py-1.5 rounded-xl text-teal-400 text-xs border border-white/5 uppercase tracking-wider">
                                            #{tag}
                                        </span>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            <div className="max-w-7xl mx-auto px-6 lg:px-12 py-20 grid grid-cols-1 lg:grid-cols-12 gap-16">
                {/* Main Content Area */}
                <div className="lg:col-span-8">
                    <button
                        onClick={() => navigate(-1)}
                        className="flex items-center space-x-2 text-slate-400 hover:text-teal-600 mb-12 font-bold transition-all group lg:-ml-4"
                    >
                        <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
                        <span className="uppercase text-xs tracking-widest">Return to Itinerary</span>
                    </button>

                    <article className="prose prose-xl prose-slate max-w-none 
                        prose-headings:text-slate-900 prose-headings:font-black prose-headings:tracking-tight
                        prose-h1:text-5xl prose-h2:text-3xl prose-h2:mt-16 prose-h2:mb-8 prose-h2:pb-4 prose-h2:border-b prose-h2:border-slate-100
                        prose-p:text-slate-600 prose-p:leading-[1.8] prose-p:text-lg
                        prose-blockquote:italic prose-blockquote:text-teal-900 prose-blockquote:bg-teal-50/50 prose-blockquote:border-teal-500 prose-blockquote:rounded-2xl prose-blockquote:p-8
                        prose-strong:text-slate-900 prose-strong:font-bold
                        prose-li:text-slate-600">
                        <ReactMarkdown
                            remarkPlugins={[remarkGfm]}
                            rehypePlugins={[rehypeRaw]}
                            components={{
                                p: ({ node, ...props }) => (
                                    <p className="mb-8 leading-[1.8] text-slate-600 text-lg last:mb-0" {...props} />
                                ),
                                h1: ({ node, ...props }) => (
                                    <h1 className="text-4xl font-black text-slate-900 mt-16 mb-8 tracking-tight" {...props} />
                                ),
                                h2: ({ node, ...props }) => (
                                    <h2 className="relative group flex items-center mt-20 mb-10 pt-8" {...props}>
                                        <span className="absolute -left-8 opacity-0 group-hover:opacity-100 transition-all duration-300 text-teal-400 font-black text-xl translate-x-4 group-hover:translate-x-0">/</span>
                                        <span className="text-slate-900 border-b-4 border-teal-500/10 pb-2">{props.children}</span>
                                    </h2>
                                ),
                                h3: ({ node, ...props }) => (
                                    <h3 className="text-2xl font-bold text-slate-900 mt-12 mb-6" {...props} />
                                ),
                                a: ({ node, ...props }) => (
                                    <a
                                        {...props}
                                        className="text-teal-600 font-bold underline decoration-teal-600/30 decoration-2 underline-offset-4 hover:decoration-teal-600 transition-all hover:text-teal-700 inline-flex items-center gap-1"
                                    >
                                        {props.children}
                                        <ExternalLink className="w-3 h-3 opacity-50" />
                                    </a>
                                ),
                                img: ({ node, ...props }) => (
                                    <div className="my-12 relative group">
                                        <div className="absolute inset-0 bg-teal-500/10 blur-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-700 rounded-full" />
                                        <img {...props} className="relative z-10 rounded-[2rem] shadow-2xl w-full object-cover max-h-[600px] border border-slate-100" />
                                        {props.alt && (
                                            <div className="mt-4 flex items-center justify-center space-x-2 text-slate-400 italic">
                                                <div className="w-8 h-[1px] bg-slate-200" />
                                                <span className="text-sm font-medium">{props.alt}</span>
                                                <div className="w-8 h-[1px] bg-slate-200" />
                                            </div>
                                        )}
                                    </div>
                                ),
                                blockquote: ({ node, ...props }) => (
                                    <div className="my-16 relative">
                                        <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-gradient-to-b from-teal-500 to-teal-200 rounded-full" />
                                        <blockquote className="pl-10 pr-6 py-4 italic text-2xl font-medium text-slate-800 leading-relaxed bg-slate-50/50 rounded-r-3xl border-y border-r border-slate-100/50">
                                            {props.children}
                                        </blockquote>
                                        <span className="absolute -top-8 left-4 text-8xl text-teal-500/10 font-serif pointer-events-none">"</span>
                                    </div>
                                ),
                                table: ({ node, ...props }) => (
                                    <div className="my-12 overflow-hidden rounded-3xl border border-slate-100 shadow-xl bg-white">
                                        <table className="w-full text-left" {...props} />
                                    </div>
                                ),
                                thead: ({ node, ...props }) => (
                                    <thead className="bg-slate-50 border-b border-slate-100" {...props} />
                                ),
                                th: ({ node, ...props }) => (
                                    <th className="px-8 py-5 text-sm font-black uppercase tracking-wider text-slate-900" {...props} />
                                ),
                                td: ({ node, ...props }) => (
                                    <td className="px-8 py-5 text-slate-600 border-b border-slate-50 last:border-0" {...props} />
                                )
                            }}
                        >
                            {blog.content}
                        </ReactMarkdown>
                    </article>

                    {/* Social Interaction Bar */}
                    <div className="mt-24 pt-10 border-t border-slate-100 flex flex-col md:flex-row items-center justify-between gap-6 bg-slate-50/50 p-8 rounded-3xl">
                        <div>
                            <p className="text-xl font-black text-slate-900 mb-1">Was this guide helpful?</p>
                            <p className="text-slate-500 font-medium">Share this journey with your fellow adventurers.</p>
                        </div>
                        <div className="flex items-center gap-4">
                            <div className="flex items-center gap-4">
                                <button
                                    onClick={handleLike}
                                    className={`flex items-center space-x-2 px-6 py-4 rounded-2xl font-bold transition-all ${userInteraction === 'like'
                                        ? 'bg-teal-50 text-teal-600 border border-teal-200'
                                        : 'bg-white text-slate-600 hover:text-teal-600 hover:shadow-md border border-slate-200'
                                        }`}
                                >
                                    <ThumbsUp className={`w-5 h-5 ${userInteraction === 'like' ? 'fill-current' : ''}`} />
                                    <span>{likes}</span>
                                </button>

                                <button
                                    onClick={handleUnlike}
                                    className={`flex items-center space-x-2 px-6 py-4 rounded-2xl font-bold transition-all ${userInteraction === 'unlike'
                                        ? 'bg-red-50 text-red-500 border border-red-200'
                                        : 'bg-white text-slate-600 hover:text-red-500 hover:shadow-md border border-slate-200'
                                        }`}
                                >
                                    <ThumbsDown className={`w-5 h-5 ${userInteraction === 'unlike' ? 'fill-current' : ''}`} />
                                    <span>{unlikes}</span>
                                </button>

                                <button
                                    onClick={handleShare}
                                    className="flex items-center space-x-3 bg-teal-600 text-white font-bold px-8 py-4 rounded-2xl shadow-lg shadow-teal-500/30 hover:shadow-teal-500/40 hover:-translate-y-1 transition-all active:scale-95"
                                >
                                    <Share2 className="w-5 h-5" />
                                    <span>Share ({shares})</span>
                                </button>
                            </div>
                        </div>
                    </div>


                    {/* Horizontal Banner */}
                    <div className="mt-12 flex justify-center w-full">
                        <AffiliateBanner bannerType="horizontal-banner" className="w-full max-w-4xl" />
                    </div>
                </div>

                {/* Glassmorphism Sidebar */}
                <div className="lg:col-span-4 lg:block">
                    <div className="sticky top-32 space-y-10">
                        <div className="bg-white/70 backdrop-blur-3xl rounded-[2.5rem] p-8 shadow-[0_32px_64px_-16px_rgba(0,0,0,0.1)] border border-white/50 relative overflow-hidden">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-teal-500/10 rounded-full -mr-16 -mt-16 blur-3xl" />

                            <div className="relative z-10">
                                <div className="flex items-center justify-between mb-10">
                                    <h3 className="text-2xl font-black text-slate-900 tracking-tight">Curated Matches</h3>
                                    <div className="bg-teal-500 text-white p-2 rounded-xl shadow-lg shadow-teal-500/40">
                                        <Tag className="w-4 h-4" />
                                    </div>
                                </div>

                                {relatedProducts.length > 0 ? (
                                    <div className="space-y-4 max-h-[600px] overflow-y-auto pr-2 custom-scrollbar">
                                        {relatedProducts.map((product, idx) => (
                                            <div
                                                key={product.id}
                                                className="group"
                                                onClick={() => navigate(`/user/best-deals?product_id=${product.id}`)}
                                            >
                                                <HorizontalProductCard product={product} onClick={() => { }} />
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="bg-slate-50 rounded-2xl p-8 border border-slate-100 text-center">
                                        <p className="text-slate-400 text-sm font-medium mb-6 italic leading-relaxed">
                                            Scanning for semantic similarity... Try wandering to our <span className="text-teal-600 font-bold">Best Deals</span> catalog for more.
                                        </p>
                                        <button
                                            onClick={() => navigate('/user/best-deals')}
                                            className="w-full py-4 bg-white text-slate-900 border border-slate-200 rounded-xl font-black text-sm hover:bg-slate-50 transition-colors"
                                        >
                                            Explore Everything
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Affiliate Banner */}
                        <div className="hidden lg:flex justify-center">
                            <AffiliateBanner bannerType="vertical-banner" className="bg-transparent" />
                        </div>

                        {/* SEO / Info Card */}
                        <div className="p-8 bg-gray-900 rounded-[2.5rem] text-white overflow-hidden relative group">
                            <div className="absolute bottom-0 right-0 w-48 h-48 bg-teal-500/20 rounded-full -mb-24 -mr-24 blur-3xl group-hover:bg-teal-500/30 transition-all duration-700" />
                            <h4 className="text-sm font-black uppercase tracking-[0.2em] mb-4 text-teal-400">Authority Note</h4>
                            <p className="text-gray-400 text-sm leading-relaxed relative z-10">
                                This guide is curated using WanderWriter's semantic engine. All linked deal matches are based on geographic proximity and thematic alignment.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div >
    );
};

export default BlogViewerPage;
