import React from 'react';
import { Message, TripPlanData, WeatherData, DayPlan } from '../../../types';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { TripPlanPreviewCard } from './TripPlanPreviewCard';
import { WeatherPreviewCard } from './WeatherComponents/WeatherPreviewCard';
import { MapPreviewCard } from './MapPreviewCard';
import { generateTripPlanHtml } from '../services/htmlGenerator';

interface MessageBubbleProps {
  message: Message;
  onPlanClick?: (plan: TripPlanData) => void;
  onWeatherClick?: (weather: WeatherData) => void;
  onMapClick?: (dayPlan: DayPlan) => void;
}

const BotIcon = () => (
  <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-purple-500 to-teal-400 flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
    TA
  </div>
);

const UserIcon = () => (
  <div className="w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
    AS
  </div>
);

export const MessageBubble: React.FC<MessageBubbleProps> = ({
  message,
  onPlanClick,
  onWeatherClick,
  onMapClick
}) => {
  const isUser = message.role === 'user';
  const content = message.content;

  // Render content based on MessageContent properties
  const renderContent = () => {
    // Render trip plan if available
    if (content.plan) {
      const planData = content.plan;

      return (
        <div
          onClick={() => onPlanClick?.(planData)}
          className="cursor-pointer"
        >
          <TripPlanPreviewCard
            url="#"
            title={planData.title}
            heroImageText={planData.heroImageText || planData.title}
            imageUrl={planData.heroImageUrl}
            planId={message.id}
            onViewClick={() => onPlanClick?.(planData)}
          />
        </div>
      );
    }

    // Render weather if available
    if (content.weather) {
      return (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
          <WeatherPreviewCard
            data={content.weather}
            onViewClick={() => onWeatherClick?.(content.weather!)}
          />
        </div>
      );
    }

    // Render image if available
    if (content.imageUrl) {
      return (
        <img
          src={content.imageUrl}
          alt="Generated by AI"
          className="rounded-lg shadow-md max-w-full"
        />
      );
    }

    // Render day plan map if available
    if (content.dayPlan) {
      return (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
          <MapPreviewCard
            dayPlan={content.dayPlan}
            onViewMap={() => onMapClick?.(content.dayPlan!)}
          />
        </div>
      );
    }

    // Render text with Markdown
    return (
      <div className={`prose prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-gray-800 prose-pre:text-gray-100 ${content.isLimit ? 'text-red-600 font-bold' : ''}`}>
        <Markdown
          remarkPlugins={[remarkGfm]}
          components={{
            p: ({ node, ...props }) => <p className="mb-4 last:mb-0" {...props} />,
            h1: ({ node, ...props }) => <h1 className="text-xl font-bold mb-4" {...props} />,
            h2: ({ node, ...props }) => <h2 className="text-lg font-bold mb-3" {...props} />,
            h3: ({ node, ...props }) => <h3 className="text-md font-bold mb-2" {...props} />,
            ul: ({ node, ...props }) => <ul className="list-disc pl-5 mb-4" {...props} />,
            ol: ({ node, ...props }) => <ol className="list-decimal pl-5 mb-4" {...props} />,
            li: ({ node, ...props }) => <li className="mb-1" {...props} />,
            table: ({ node, ...props }) => (
              <div className="overflow-x-auto mb-4">
                <table className="min-w-full border-collapse border border-gray-300 rounded-lg overflow-hidden" {...props} />
              </div>
            ),
            thead: ({ node, ...props }) => <thead className="bg-gray-100" {...props} />,
            th: ({ node, ...props }) => <th className="border border-gray-300 px-4 py-2 text-left font-semibold" {...props} />,
            td: ({ node, ...props }) => <td className="border border-gray-300 px-4 py-2" {...props} />,
            code: ({ node, ...props }) => <code className="bg-gray-100 px-1 py-0.5 rounded text-pink-600 font-mono text-sm" {...props} />,
          }}
        >
          {content.text}
        </Markdown>
        {content.isLimit && (
          <div className="mt-4">
            <button
              onClick={() => window.location.href = '#/user/subscription'}
              className="bg-red-600 text-white px-6 py-2 rounded-xl text-sm font-bold shadow-lg hover:bg-red-700 transition-all transform hover:scale-105 active:scale-95"
            >
              Upgrade Now
            </button>
          </div>
        )}
      </div>
    );

    // Fallback
    return <div className="text-sm">No content to display</div>;
  };

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`max-w-2xl w-full ${isUser ? 'items-end' : 'items-start'} flex flex-col`}>
        <div className={`flex items-start gap-2.5 ${isUser ? 'flex-row-reverse' : ''}`}>
          {!isUser ? <BotIcon /> : <UserIcon />}

          <div
            className={`p-4 rounded-b-xl shadow-sm ${isUser
              ? 'bg-teal-600 rounded-tl-xl text-white'
              : 'bg-gray-50 border border-gray-100 rounded-tr-xl text-gray-800'
              }`}
          >
            {renderContent()}
          </div>
        </div>
      </div>
    </div>
  );
};